credentials:
  usernames:
    sara:
      name: Sara van Oordt
      password: $2b$12$pxXJKS25fmUi42ydtE06qelu7fIvIBmvVDMPaoVAHFv.FcvHCj/mG # To be replaced with hashed password
    salome:
      name: Salome Straumann
      password: $2b$12$356qGxYjo.0I6Cy5U4zhROctJyhLmCy1c1GsIE2kUMzrhDVEQC9ue # To be replaced with hashed password
    fabienne:
      name: Fabienne Schätti
      password: $2b$12$9ZaAhUkOB14ZFgKJVusl9uxx7djeyrkSFUu22xWGOFjKrwdB.xzAi # To be replaced with hashed password
    samuel:
      name: Samuel Wehrli
      password: $2b$12$J926bfHEsp0jUHKEdPCh7.7SmDgreSKjLdCZUWE.ILxKDm8HVEvMa # To be replaced with hashed password
    guest:
      name: Gast
      password: $2b$12$p.tNIg7woLHg.BkbJc8r6eDtaozl0Tbr2rTrvpmyxfk.8i05UX2Zi # To be replaced with hashed password
          
      
cookie:
  expiry_days: 30  # number of days until password is asked again
  key: JgDyEoKUNItM5prxo194jDeLYzVzmYE6 # Must be string, use https://randomkeygen.com/
  name: streamlitcookie